[package]
authors = ["Sebastian <sb@pus.de>"]
name = "aruna-file"
version = "0.2.0-rc.1"
edition = "2021"
repository = "https://github.com/ArunaStorage/aruna-file"
license = "MIT OR Apache-2.0"
description = "Library and component for encrypting / compressing .aruna files, including specification"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
async-compression = {version = "0.3.15", features = ["tokio", "zstd"]}
hex = "0.4"
chacha20poly1305 = "0.10.1"
byteorder = "1.4.3"
bytes = "1.4.0"
tokio = {version = "1.25.0", features = ["full"]}
async-trait = "0.1.66"
hyper = {version = "0.14.25", features = ["full"]}
futures = "0.3.27"
async-channel = "1.8.0"
async-stream = "0.3.4"
log = "0.4.17"
tar = "0.4.38"
serde = {version = "1.0.163", features = ["derive"]}
serde_json = "1.0.96"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports", "async_tokio"] }

[[bench]]
name = "performance"
harness = false