[package]
authors = ["Sebastian Beyvers <sb@pus.de>"]
name = "pithos"
version = "0.5.0"
edition = "2021"
repository = "https://github.com/ArunaStorage/aruna-file"
license = "MIT OR Apache-2.0"
description = "Library and component for encrypting / compressing .pth files, including specification"

[dependencies]
pithos_lib = { path = "../pithos_lib" }